# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bigrecord-driver}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["openplaces.org"]
  s.date = %q{2009-09-28}
  s.default_executable = %q{hbase-driver}
  s.email = %q{bigrecord@openplaces.org}
  s.executables = ["hbase-driver", "cassandra-driver"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.homepage = %q{http://www.bigrecord.org}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{BigRecord drivers implemented as JRuby DRb servers.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
