require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/gempackagetask'

#Gem::manage_gems

spec = Gem::Specification.new do |s| 
  s.platform = Gem::Platform::RUBY
  s.name = "bigrecord-driver"
  s.version = "0.0.1"
  s.author = "BigRecord"
  s.email = "bigrecord@openplaces.org "
  s.homepage = "http://www.bigrecord.org"
  s.summary = "HBase driver implemented as a JRuby DRb server."
  s.files = FileList["{bin,lib,vendor,test,conf}/**/*"].to_a
  s.require_path = "lib"
  s.test_files = FileList["{test}/**/*test.rb"].to_a
  s.has_rdoc = true
  s.extra_rdoc_files = ["README"]
  s.bindir = 'bin'
  s.executables = ['hbase-driver', 'cassandra-driver']
  s.default_executable = 'hbase-driver'
  #s.add_dependency("dependency", ">= 0.x.x")
end

Rake::GemPackageTask.new(spec) do |pkg| 
  pkg.need_tar = true 
end 

task :default => "pkg/#{spec.name}-#{spec.version}.gem" do
  puts "generated latest version"
end

desc "Run the tests"
Rake::TestTask::new do |t|
    t.test_files = FileList['test/test*.rb']
    t.verbose = true
end
