require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/gempackagetask'

begin
  require 'jeweler'

  Jeweler::Tasks.new do |gemspec|
    gemspec.name = "bigrecord-driver"
    gemspec.authors = ["openplaces.org"]
    gemspec.email = "bigrecord@openplaces.org"
    gemspec.homepage = "http://www.bigrecord.org"
    gemspec.summary = "Bigrecord drivers implemented as JRuby DRb servers"
    gemspec.description = "Bigrecord drivers that use JRuby DRb servers to connect with databases through their native Java APIs. Currently supported databases are HBase and Cassandra."
    gemspec.executables = ['hbase-driver', 'cassandra-driver', 'launcher']
    gemspec.default_executable = 'hbase-driver'
    gemspec.files = FileList["{bin,conf,lib,test,vendor}/**/*","MIT-LICENSE", "README.rdoc", "VERSION"].to_a
    gemspec.extra_rdoc_files = FileList["MIT-LICENSE","README.rdoc"].to_a
  end
rescue LoadError
  puts "Jeweler not available. Install it with: sudo gem install technicalpickles-jeweler -s http://gems.github.com"
end

desc "Run the tests"
Rake::TestTask::new do |t|
    t.test_files = FileList['test/test*.rb']
    t.verbose = true
end
