#!/usr/bin/env ruby

require 'rubygems'
require 'rake'
require 'rake/rdoctask'
require 'rake/gempackagetask'
require 'pathname'
require 'spec/rake/spectask'


DATA_STORES = ["hbase", "cassandra"]
ROOT = Pathname(__FILE__).dirname.expand_path

require ROOT + 'tasks/gem'
require ROOT + 'tasks/rdoc'
require ROOT + 'tasks/spec'
require ROOT + 'tasks/data_store'
