require 'rubygems'

DATA_STORES = ["hbase", "cassandra"]
ROOT = File.expand_path(File.dirname(__FILE__)) + '/'

require ROOT + 'tasks/data_store.rb'
require ROOT + 'tasks/gem.rb'
require ROOT + 'tasks/rdoc.rb'
require ROOT + 'tasks/spec.rb'
